### ISSUE TITLE
Crash in 1.18.1-rc.1 - Breaker ticked on crash.

### ISSUE THREAD

**Issue by MattB70** [Shnupbups/redstone-bits#17]
**1.18.1-rc.1**
_Paired with a few other mods, some modified to be forced to run on .1-rc.1
**I don't expect a fix**, just reporting._

-- Block entity being ticked --
Details:
Name: redstonebits:breaker // com.shnupbups.redstonebits.blockentity.BreakerBlockEntity
Block: Block{redstonebits:breaker}[breaking=false,facing=down,triggered=true]
Block location: World: (-394,67,-691), Section: (at 6,3,13 in -25,4,-44; chunk contains blocks -400,-64,-704 to -385,319,-689), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
Block: Block{minecraft:void_air}
Block location: World: (-394,67,-691), Section: (at 6,3,13 in -25,4,-44; chunk contains blocks -400,-64,-704 to -385,319,-689), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
Block Entity NBT: {BreakProgress:0,BreakStack:{Count:1b,id:"minecraft:air"},Items:[]}
Stacktrace:
at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
at net.minecraft.class_1937.method_18471(class_1937.java:477)
at net.minecraft.class_638.method_18116(class_638.java:205)
at net.minecraft.class_310.method_1574(class_310.java:1751)
at net.minecraft.class_310.method_1523(class_310.java:1086)
at net.minecraft.class_310.method_1514(class_310.java:733)
at net.minecraft.client.main.Main.main(Main.java:236)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Raidobw2** [comment]
Got that one too, but on 1.18, not 1.18.1.
Full crash report: https://pastebin.com/C4Trbv3G
That's a custom modpack, not one you'll find on CF.

How to reproduce:
1. Create yourself a new 1.18 instance on CurseForge with Fabric.
2. Add Fabric Waystones and Redstone Bits.
3. Place down 2 waystones far from each other and right-click to learn them.
4. On one end, place the breaker. In front, place a cobblestone block or any block. Give it a pickaxe, any pickaxe. Not sure if either of those steps matter, but that reproduces the setup I have. Don't power the breaker, leave the block in front.
5. Use the waystone to tp out of there while the breaker is just sitting there idle.
6. Game crashes.

Cool mod, and most balanced block breaker I've ever seen. Applies speed, fortune and silk touch too, it stays true to the vanilla game. Thanks for making it. Hope that one helps you out finding the issue in a future release. :)

**Comment by Shnupbups** [comment]
Should be fixed in latest

**Comment by Raidobw2** [comment]
Awesome! Much thanks to you and kjanei!
