### ISSUE TITLE
Crash on breaker breaking a block, 1.16.2

### ISSUE THREAD

**Issue by matthew-cline** [Shnupbups/redstone-bits#9]
I placed down a breaker, put a stone pickaxe in it, placed a cobblestone block in front of the breaker, and put a redstone torch down next to the breaker.  When the block finally breaks the game crashes.

**Minecraft**: 1.16.2
**World**: superflat, creative mode, cheating on
**JDK**: Oracle 12.0.2
**OS**: Linux x64 (Fedora 32)

Top of stack trace:
```
java.lang.NoSuchMethodError: net.minecraft.class_1657.<init>(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lcom/mojang/authlib/GameProfile;)V
    at com.shnupbups.redstonebits.FakePlayerEntity.<init>(FakePlayerEntity.java:18)
```

Full crash report is here [here](https://github.com/Shnupbups/redstone-bits/files/5079594/crash-report.txt).

**Comment by ShadowFoxNixill** [comment]
Was able to reproduce.

**Minecraft:** 1.16.3
**World:** normal, creative, cheating on
**JDK:** Pretty sure Minecraft on Windows ignores your installed JDK and uses its bundled Java 8.
**OS:** Windows 10 64-bit

Same stack trace as above.

**Comment by campbebj** [comment]
Minecraft 1.16.4
survival, no cheating
bundled java 8 on windows 64bit.


net.minecraft.class_148: Ticking block entity
--
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1657.<init>(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lcom/mojang/authlib/GameProfile;)V
at com.shnupbups.redstonebits.FakePlayerEntity.<init>(FakePlayerEntity.java:18) ~[redstone-bits-1.3.0+fabric-1.16.1.jar:?]
at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.breakBlock(BreakerBlockEntity.java:137) ~[redstone-bits-1.3.0+fabric-1.16.1.jar:?]
at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.finishBreak(BreakerBlockEntity.java:116) ~[redstone-bits-1.3.0+fabric-1.16.1.jar:?]
at com.shnupbups.redstonebits.blockentity.BreakerBlockEntity.method_16896(BreakerBlockEntity.java:165) ~[redstone-bits-1.3.0+fabric-1.16.1.jar:?]
at net.minecraft.class_1937.method_18471(class_1937.java:510) ~[intermediary-server.jar:?]
at net.minecraft.class_3218.method_18765(class_3218.java:429) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
... 5 more
[23:57:08] [Server thread/ERROR]: This crash report has been saved to: /config/mineos/games/servers/FabricSurival/./crash-reports/crash-2020-11-26_23.57.08-server.txt
